sudo: required

language: node_js
node_js:
  - "lts/*"
os: osx

before_install:
  - cd Office365
  - sudo curl -o- -L https://yarnpkg.com/install.sh | bash

install:
  - sudo yarn install
  - sudo yarn run dist:macos